"""High-level facade tying file store + index + snapshot manager.

This is what tools depend on. It owns the in-memory index, persists writes
to JSON shards, and records every mutation as a ChangeEntry pending the next
``commit_snapshot()`` call.

V0 sharding choice: all entities go in ``shared/entities.json``; all relations
in ``shared/relations.json``. Target shards (per-anchor JSON files) are a
derived view generated by Stage 6 export tooling. This keeps the write path
simple while preserving the agent-friendly JSON-file ground truth.
"""

from __future__ import annotations

import copy
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from .schemas import (
    ChangeEntry,
    EntityBase,
    RelationBase,
    SnapshotMeta,
)
from .store import (
    IndexLayer,
    IndustryGraphFileStore,
    SnapshotManager,
    make_change,
)

ENTITIES_SHARD = "entities"
RELATIONS_SHARD = "relations"


def _as_dict(obj: Any) -> dict[str, Any]:
    if hasattr(obj, "model_dump"):
        return obj.model_dump(mode="json")
    return dict(obj)


class IndustryGraphStore:
    """High-level orchestrator.

    Construct → ``await load()``. Then call write helpers (``upsert_entity``,
    ``upsert_relation``, ``deprecate_*``) and read helpers via the underlying
    :class:`IndexLayer` (exposed as ``self.index``).

    Mutations are persisted immediately to the JSON file store and appended
    to a ``pending`` list. A subsequent ``commit_snapshot()`` packages the
    pending changes into a numbered snapshot directory and clears the list.
    """

    def __init__(self, *, root: Path | None = None) -> None:
        self.fs = IndustryGraphFileStore(root=root)
        self.snapshots = SnapshotManager(self.fs)
        self.index = IndexLayer()
        self._pending: list[ChangeEntry] = []
        self._loaded = False

    # ---------- lifecycle ----------
    async def load(self) -> None:
        """Read shards from disk and rebuild the in-memory index. Idempotent."""
        entities = await self.fs.load_shared(ENTITIES_SHARD) or {}
        relations = await self.fs.load_shared(RELATIONS_SHARD) or {}
        self.index = IndexLayer()
        self.index.bulk_load(
            entities=list(entities.values()),
            relations=list(relations.values()),
        )
        self._loaded = True

    async def _persist_entities(self) -> None:
        await self.fs.persist_shared(ENTITIES_SHARD, dict(self.index.by_id))

    async def _persist_relations(self) -> None:
        await self.fs.persist_shared(RELATIONS_SHARD, dict(self.index.relations_by_id))

    def stats(self) -> dict[str, int]:
        s = self.index.stats()
        s["pending_changes"] = len(self._pending)
        return s

    @property
    def pending(self) -> list[ChangeEntry]:
        return list(self._pending)

    # ---------- entity write ----------
    async def upsert_entity(
        self,
        entity: EntityBase | dict[str, Any],
        *,
        source_ref_id: str | None,
        actor: str | None = None,
    ) -> dict[str, Any]:
        """Insert or merge an entity. Returns ``{action, entity, diff}``.

        Action is one of ``created``, ``updated``, ``unchanged``. ``diff`` is
        the difference between before and after (top-level keys whose value
        changed). Source-ref ID may be ``None`` only when the caller is
        ingesting a Source itself (chicken-and-egg).
        """
        record = _as_dict(entity)
        eid = record["id"]
        now = datetime.now(UTC).isoformat()
        existing = self.index.by_id.get(eid)
        if existing is None:
            record.setdefault("created_at", now)
            record.setdefault("updated_at", now)
            self.index.add_entity(record)
            await self._persist_entities()
            change = make_change(
                op="insert",
                kind="entity",
                id=eid,
                after=copy.deepcopy(record),
                source_ref_id=source_ref_id,
                actor=actor,
            )
            self._pending.append(change)
            await self.fs.append_audit(_audit_entry(change))
            return {"action": "created", "entity": record, "diff": record}

        merged = _merge_entity(existing, record, now=now)
        if merged == existing:
            return {"action": "unchanged", "entity": existing, "diff": {}}

        diff = _shallow_diff(existing, merged)
        self.index.add_entity(merged)  # replaces under same id
        await self._persist_entities()
        change = make_change(
            op="update",
            kind="entity",
            id=eid,
            before=copy.deepcopy(existing),
            after=copy.deepcopy(merged),
            source_ref_id=source_ref_id,
            actor=actor,
        )
        self._pending.append(change)
        await self.fs.append_audit(_audit_entry(change))
        return {"action": "updated", "entity": merged, "diff": diff}

    async def deprecate_entity(
        self,
        entity_id: str,
        *,
        reason: str,
        source_ref_id: str | None,
        actor: str | None = None,
    ) -> dict[str, Any]:
        existing = self.index.by_id.get(entity_id)
        if existing is None:
            return {"action": "missing", "entity_id": entity_id}
        before = copy.deepcopy(existing)
        marker = datetime.now(UTC).isoformat()
        existing["deprecated_at"] = marker
        existing.setdefault("attributes", {})["deprecation_reason"] = reason
        self.index.add_entity(existing)
        await self._persist_entities()
        change = make_change(
            op="deprecate",
            kind="entity",
            id=entity_id,
            before=before,
            after=copy.deepcopy(existing),
            source_ref_id=source_ref_id,
            actor=actor,
        )
        self._pending.append(change)
        await self.fs.append_audit(_audit_entry(change))
        return {"action": "deprecated", "entity": existing}

    # ---------- relation write ----------
    async def upsert_relation(
        self,
        relation: RelationBase | dict[str, Any],
        *,
        source_ref_id: str,
        actor: str | None = None,
    ) -> dict[str, Any]:
        record = _as_dict(relation)
        rid = record["id"]
        now = datetime.now(UTC).isoformat()
        existing = self.index.relations_by_id.get(rid)
        if existing is None:
            record.setdefault("created_at", now)
            record.setdefault("updated_at", now)
            self.index.add_relation(record)
            await self._persist_relations()
            change = make_change(
                op="insert",
                kind="relation",
                id=rid,
                after=copy.deepcopy(record),
                source_ref_id=source_ref_id,
                actor=actor,
            )
            self._pending.append(change)
            await self.fs.append_audit(_audit_entry(change))
            return {"action": "created", "relation": record, "diff": record}

        merged = _merge_relation(existing, record, now=now)
        if merged == existing:
            return {"action": "unchanged", "relation": existing, "diff": {}}
        diff = _shallow_diff(existing, merged)
        # Replace under same key: remove + re-add for clean graph edge state.
        self.index.remove_relation(rid)
        self.index.add_relation(merged)
        await self._persist_relations()
        change = make_change(
            op="update",
            kind="relation",
            id=rid,
            before=copy.deepcopy(existing),
            after=copy.deepcopy(merged),
            source_ref_id=source_ref_id,
            actor=actor,
        )
        self._pending.append(change)
        await self.fs.append_audit(_audit_entry(change))
        return {"action": "updated", "relation": merged, "diff": diff}

    async def deprecate_relation(
        self,
        relation_id: str,
        *,
        reason: str,
        source_ref_id: str,
        actor: str | None = None,
    ) -> dict[str, Any]:
        existing = self.index.relations_by_id.get(relation_id)
        if existing is None:
            return {"action": "missing", "relation_id": relation_id}
        before = copy.deepcopy(existing)
        existing["deprecated_at"] = datetime.now(UTC).isoformat()
        existing.setdefault("attributes", {})["deprecation_reason"] = reason
        self.index.remove_relation(relation_id)
        self.index.add_relation(existing)
        await self._persist_relations()
        change = make_change(
            op="deprecate",
            kind="relation",
            id=relation_id,
            before=before,
            after=copy.deepcopy(existing),
            source_ref_id=source_ref_id,
            actor=actor,
        )
        self._pending.append(change)
        await self.fs.append_audit(_audit_entry(change))
        return {"action": "deprecated", "relation": existing}

    # ---------- snapshot ----------
    async def commit_snapshot(
        self,
        *,
        rationale: str,
        created_by_run_id: str | None = None,
    ) -> SnapshotMeta:
        """Package all pending changes into a new snapshot and clear pending."""
        meta = await self.snapshots.commit(
            rationale=rationale,
            changes=self._pending,
            created_by_run_id=created_by_run_id,
        )
        self._pending = []
        return meta


# ============================================================
# Helpers
# ============================================================
def _audit_entry(c: ChangeEntry) -> dict[str, Any]:
    return c.model_dump(mode="json")


def _merge_entity(
    existing: dict[str, Any], incoming: dict[str, Any], *, now: str
) -> dict[str, Any]:
    """Conservative deep-merge: incoming wins, but list fields merge by union
    (preserving existing order and appending new), and ``attributes``/``facets``
    nested dicts merge by key. Always bumps ``updated_at``."""
    merged = copy.deepcopy(existing)
    for key, value in incoming.items():
        if key in {"created_at"}:
            continue  # never overwrite created_at
        if key in {"labels", "aliases", "provenance"} and isinstance(value, list):
            current = merged.get(key, [])
            for v in value:
                if v not in current:
                    current.append(v)
            merged[key] = current
        elif key == "attributes" and isinstance(value, dict):
            base = merged.get("attributes", {})
            base.update(value)
            merged["attributes"] = base
        elif key == "facets" and isinstance(value, dict):
            base = merged.get("facets") or {}
            for axis, v in value.items():
                if isinstance(v, list):
                    cur = base.get(axis, [])
                    for item in v:
                        if item not in cur:
                            cur.append(item)
                    base[axis] = cur
                else:
                    base[axis] = v
            merged["facets"] = base
        else:
            merged[key] = value
    merged["updated_at"] = now
    return merged


def _merge_relation(
    existing: dict[str, Any], incoming: dict[str, Any], *, now: str
) -> dict[str, Any]:
    """Incoming wins on simple fields; ``weights`` list merges by period (new
    observations append; same period gets overwritten); ``provenance``/
    ``attributes`` follow entity merge rules."""
    merged = copy.deepcopy(existing)
    for key, value in incoming.items():
        if key in {"created_at"}:
            continue
        if key == "weights" and isinstance(value, list):
            current = merged.get("weights", [])
            by_period = {w["period"]: w for w in current}
            for w in value:
                by_period[w["period"]] = w
            merged["weights"] = list(by_period.values())
        elif key in {"provenance"} and isinstance(value, list):
            cur = merged.get(key, [])
            for v in value:
                if v not in cur:
                    cur.append(v)
            merged[key] = cur
        elif key == "attributes" and isinstance(value, dict):
            base = merged.get("attributes", {})
            base.update(value)
            merged["attributes"] = base
        else:
            merged[key] = value
    merged["updated_at"] = now
    return merged


def _shallow_diff(
    before: dict[str, Any], after: dict[str, Any]
) -> dict[str, Any]:
    """Top-level keys whose values differ. Used to report write actions."""
    diff: dict[str, Any] = {}
    keys = set(before) | set(after)
    for k in keys:
        if before.get(k) != after.get(k):
            diff[k] = {"before": before.get(k), "after": after.get(k)}
    return diff
